#use_modular_headers!

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'  # You can increase this if needed
prepare_react_native_project!

# FORCE dynamic frameworks for Firebase compatibility
linkage = ENV['USE_FRAMEWORKS'] || 'dynamic'
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'BeenThere' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )

  pod 'FirebaseCore', :modular_headers => true;
  pod 'GoogleUtilities', :modular_headers => true;
  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Fix for Firebase Swift pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end
